# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-ansi --no-interaction
    - name: Build Sphinx
      run: | 
        cd docs
        make html
        touch .nojekyll
    - name: Deploy
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{secrets.GHUB_TOKEN}}
        branch: gh_pages
        force: true
        directory: docs/_build


        
